name: 'iotdb-writer'
description: 'iotdb writer'
inputs:
  version:
    description: 'IoTDB version'
    required: false
    default: iotdb11
  Test-Way:
    description: 'the way to imp'
    required: false
    default: clearData
runs:
  using: "composite" # Mandatory parameter
  steps:
    - name: Write history Data
      shell: bash
      run: |
        mv test/pom.xml test/pom.xml.backup
        mv test/pom.xml.${{inputs.version}} test/pom.xml
        mvn test -q -Dtest=IoTDBHistoryDataGenerator#${{inputs.Test-Way}} -DfailIfNoTests=false
        sleep 5