name: 'dependence-setup'
description: 'environment dependence setup'
inputs:
  python-version:
    description: 'python-version'
    required: false
    default: 3.7
  java:
    description: 'java version'
    required: false
    default: 8
  os:
    description: 'running environment'
    required: false
    default: ubuntu-latest
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
    - name: Set up JDK ${{ inputs.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2.1.5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2