name: 'dependence-setup'
description: 'environment dependence setup'
inputs:
  python-version:
    description: 'python-version'
    required: false
    default: "3.7"
  java:
    description: 'java version'
    required: false
    default: 8
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set up JDK ${{ inputs.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java }}
    - shell: bash
      run: echo "Log level"