name: 'zookeeper-runner'
description: 'zookeeper runner'
inputs:
  os:
    description: 'zookeeper runner environment'
    required: false
    default: ubuntu-latest
runs:
  using: "composite" # Mandatory parameter
  steps:
    - name: Run ZooKeeper
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
        chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
        "${GITHUB_WORKSPACE}/.github/zk.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
        chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
        "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
        else
        echo "$RUNNER_OS is not supported"
        exit 1
        fi