name: 'zookeeper-runner'
description: 'zookeeper runner'
inputs:
  os:
    description: 'zookeeper runner environment'
    required: false
    default: ubuntu-latest
  if-stop:
    description: 'to stop the zookeeper'
    required: false
    default: "false"
  if-rerun:
    description: 'to rerun the zookeeper'
    required: false
    default: "false"
runs:
  using: "composite" # Mandatory parameter
  steps:
    - if: inputs.if-stop=='false' && inputs.if-rerun=='false'
      name: Run ZooKeeper
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
        chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
        "${GITHUB_WORKSPACE}/.github/zk.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
        chmod +x "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
        "${GITHUB_WORKSPACE}/.github/zk_macos.sh"
        else
        echo "$RUNNER_OS is not supported"
        exit 1
        fi

    - if: inputs.if-rerun=='true'
      name: ReRun ZooKeeper
      shell: bash
      run: |
        zookeeper/bin/zkServer.sh start

    - if: inputs.if-stop=='true'
      name : Stop Zookeeper
      shell: bash
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/zkClear.sh"
        "${GITHUB_WORKSPACE}/.github/zkClear.sh"
