# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: 'capacity-expansion-test'
description: 'capacity-expansion-test with inputing the DB name and the Test name'
inputs:
  DB-name:
    description: 'What the DB to test'
    required: true
    default: iotdb11
  Teat-Way:
    description: 'What the Capacity Expansion'
    required: true
    default: OriHasDataExpHasData
  Test-name:
    description: 'What the IT name and Test instance that you want to test'
    required: true
    default: 'null'
  RUNNER_OS:
    description: 'What the os environmet'
    required: true
    default: ubuntu-latest
runs:
  using: "composite"
  steps:
    - name: Run IoTDB11 and change default config
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/${{input.DB-name}}_history_data.sh"
          "${GITHUB_WORKSPACE}/.github/${{input.DB-name}}_history_data.sh"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          chmod +x "${GITHUB_WORKSPACE}/.github/${{input.DB-name}}_history_data_macos.sh"
          "${GITHUB_WORKSPACE}/.github/${{input.DB-name}}_history_data_macos.sh"
        else
          echo "$RUNNER_OS is not supported"
          exit 1
        fi
        mv test/pom.xml test/pom.xml.backup
        mv test/pom.xml.${{input.DB-name}} test/pom.xml
    - name: Install with Maven
      run: mvn clean package -DskipTests
    - name: Write history Data
      run: |
        mvn test -q -Dtest=IoTDBHistoryDataGenerator#${{Teat-Way}} test -DfailIfNoTests=false
        sleep 10
    - name: Install with Maven Again
      run: |
        mv test/pom.xml test/pom.xml.${{input.DB-name}}
        mv test/pom.xml.backup test/pom.xml
        mvn clean package -DskipTests