/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.tsinghua.iginx.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-03-18")
public enum AggregateType implements org.apache.thrift.TEnum {
  MAX_TIME(0),
  MAX_VALUE(1),
  MIN_TIME(2),
  MIN_VALUE(3),
  SUM(4),
  COUNT(5),
  AVG(6),
  FIRST_TIME(7),
  FIRST_VALUE(8),
  LAST_TIME(9),
  LAST_VALUE(10);

  private final int value;

  private AggregateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static AggregateType findByValue(int value) { 
    switch (value) {
      case 0:
        return MAX_TIME;
      case 1:
        return MAX_VALUE;
      case 2:
        return MIN_TIME;
      case 3:
        return MIN_VALUE;
      case 4:
        return SUM;
      case 5:
        return COUNT;
      case 6:
        return AVG;
      case 7:
        return FIRST_TIME;
      case 8:
        return FIRST_VALUE;
      case 9:
        return LAST_TIME;
      case 10:
        return LAST_VALUE;
      default:
        return null;
    }
  }
}
