name: Cancel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: all