name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ZK-Test:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [ 8 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os}}
    env:
      STORAGE: zookeeper
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run ZooKeeper
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/zk.sh"
          "${GITHUB_WORKSPACE}/.github/zk.sh"
      - name: Run ETCD
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/etcd.sh"
          "${GITHUB_WORKSPACE}/.github/etcd.sh"
      - name: Run Test For Meta Manager
        run: mvn test -q -Dtest=*Test,IMetaManagerTest -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
  ETCD-Test:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [ 8 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os}}
    env:
      STORAGE: etcd
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run ETCD
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/etcd.sh"
          "${GITHUB_WORKSPACE}/.github/etcd.sh"
      - name: Run Test For Meta Manager
        run: mvn test -q -Dtest=*Test,IMetaManagerTest -DfailIfNoTests=false
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov